# By default, spring.cloud.azure.active-directory.environment property has value `global`,
# supported value is global, cn. Please refer to the README for details.
# spring.cloud.azure.active-directory.environment=global
spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        tenant-id: <your-tenant-id>
        client-id: <your-client-id>
        client-secret: <your-client-secret>
        # Optional, default value is http://localhost:8080/
        # redirect-uri-template: <your-redirect-uri>
        # groups that you created in your Azure AD tenant
        user-group:
          allowed-groups: group1,group2
        # Optional, the default value is
        # environment: global


