export AZURE_EVENTHUBS_NAMESPACE=$(terraform -chdir=./terraform output -raw AZURE_EVENTHUBS_NAMESPACE)
export AZURE_EVENTHUB_NAME=$(terraform -chdir=./terraform output -raw AZURE_EVENTHUB_NAME)

echo AZURE_EVENTHUBS_NAMESPACE=$AZURE_EVENTHUBS_NAMESPACE
echo AZURE_EVENTHUB_NAME=$AZURE_EVENTHUB_NAME
