azure:
  keyvault:
    uri: ${KEY_VAULT_URI}                # The URI to the Azure Key Vault used
    tenant-id: ${SERVICE_PRINCIPAL_TETANT}          # The Tenant ID for your Azure Key Vault (needed if you are not using managed identity).
    client-id: ${SERVICE_PRINCIPAL_ID}          # (service principal application id)The Client ID that has been setup with access to your Azure Key Vault (needed if you are not using managed identity).
    client-secret: ${SERVICE_PRINCIPAL_SECRET}      # (client secret value)The Client Secret that will be used for accessing your Azure Key Vault (needed if you are not using managed identity).
    # managed-identity:  # client-id of the user-assigned managed identity to use.
    # If the above 4 properties are empty, then system-assigned managed identity will be used.
  #cert-path:
    #well-known:  # Optional local certificates path. Your local path that holds the well-known certificates.
    #custom: # Optional local certificates path. Your local path that holds your customized certificates.
server:
  port: 8080
