$env:AZURE_SERVICEBUS_NAMESPACE=$(terraform -chdir=terraform output -raw AZURE_SERVICEBUS_NAMESPACE)
$env:AZURE_SERVICEBUS_QUEUE_NAME=$(terraform -chdir=terraform output -raw AZURE_SERVICEBUS_QUEUE_NAME)
$env:AZURE_SERVICEBUS_SUBSCRIPTION_ID=$(terraform -chdir=terraform output -raw AZURE_SERVICEBUS_SUBSCRIPTION_ID)
$env:AZURE_SERVICEBUS_RESOURCE_GROUP=$(terraform -chdir=terraform output -raw AZURE_SERVICEBUS_RESOURCE_GROUP)

echo AZURE_SERVICEBUS_NAMESPACE=$env:AZURE_SERVICEBUS_NAMESPACE
echo AZURE_SERVICEBUS_QUEUE_NAME=$env:AZURE_SERVICEBUS_QUEUE_NAME
echo AZURE_SERVICEBUS_SUBSCRIPTION_ID=$env:AZURE_SERVICEBUS_SUBSCRIPTION_ID
echo AZURE_SERVICEBUS_RESOURCE_GROUP=$env:AZURE_SERVICEBUS_RESOURCE_GROUP
