spring:
  jms:
    servicebus:
      connection-string: ${SERVICEBUS_NAMESPACE_CONNECTION_STRING}
      idle-timeout: 1800000
      pricing-tier: ${PRICING_TIER}
      topic-client-id: ${TOPIC_CLIENT_ID}




