spring:
  cloud:
    azure:
      credential:
        managed-identity-client-id: [managed-identity-client-id]
      profile:
        tenant-id: [tenant-id]
#     Uncomment below configurations if you want to enable auto creating resources.
#        subscription-id: [subscription-id]
#        cloud: Azure
#      resource:
#        region: [region]

      servicebus:
        namespace: [servicebus-namespace]
