spring:
  cloud:
    azure:
      eventgrid:
        endpoint: ${AZURE_EVENTGRID_ENDPOINT}
        key: ${AZURE_EVENTGRID_KEY}
      servicebus:
        connection-string: ${AZURE_SERVICEBUS_CONNECTION_STRING}
    function:
      definition: consume
    stream:
      bindings:
        consume-in-0:
          destination: ${AZURE_SERVICEBUS_QUEUE_NAME}
      servicebus:
        bindings:
          consume-in-0:
            consumer:
              auto-complete: false
