$env:AZURE_EVENTHUBS_CONNECTION_STRING=$(terraform -chdir=terraform output -raw AZURE_EVENTHUBS_CONNECTION_STRING)
$env:EVENTHUBS_KAFKA=$(terraform -chdir=terraform output -raw EVENTHUBS_KAFKA)
$env:AZURE_EVENTHUBS_SUBSCRIPTION_ID=$(terraform -chdir=terraform output -raw AZURE_EVENTHUBS_SUBSCRIPTION_ID)
$env:AZURE_EVENTHUBS_RESOURCE_GROUP=$(terraform -chdir=terraform output -raw AZURE_EVENTHUBS_RESOURCE_GROUP)
$env:AZURE_EVENTHUBS_NAMESPACE=$(terraform -chdir=terraform output -raw AZURE_EVENTHUBS_NAMESPACE)

echo AZURE_EVENTHUBS_CONNECTION_STRING=$env:AZURE_EVENTHUBS_CONNECTION_STRING
echo EVENTHUBS_KAFKA=$env:EVENTHUBS_KAFKA
echo AZURE_EVENTHUBS_SUBSCRIPTION_ID=$env:AZURE_EVENTHUBS_SUBSCRIPTION_ID
echo AZURE_EVENTHUBS_RESOURCE_GROUP=$env:AZURE_EVENTHUBS_RESOURCE_GROUP
echo AZURE_EVENTHUBS_NAMESPACE=$env:AZURE_EVENTHUBS_NAMESPACE
