# Please fill these placeholders before running this application:
# 1. ${TENANT_ID}
# 2. ${CLIENT_1_CLIENT_ID}
# 3. ${CLIENT_1_CLIENT_SECRET}
# 4. ${RESOURCE_SERVER_1_CLIENT_ID}
# 5. ${RESOURCE_SERVER_2_CLIENT_ID}

logging:
  level:
    root: DEBUG
server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        provider: # Refs: https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2login-common-oauth2-provider
          azure-active-directory:
            issuer-uri: https://login.microsoftonline.com/${TENANT_ID}/v2.0 # Refs: https://docs.spring.io/spring-security/site/docs/current/reference/html5/#webflux-oauth2-login-openid-provider-configuration
            user-name-attribute: name
        registration:
          client-1-resource-server-1:
            provider: azure-active-directory
            client-name: client-1-resource-server-1
            client-id: ${CLIENT_1_CLIENT_ID}
            client-secret: ${CLIENT_1_CLIENT_SECRET}
            scope: openid, profile, api://${RESOURCE_SERVER_1_CLIENT_ID}/resource-server-1.scope-1 # Refs: https://docs.microsoft.com/azure/active-directory/develop/v2-permissions-and-consent#openid-connect-scopes
            redirect-uri: http://localhost:8080/login/oauth2/code/
          client-1-resource-server-2:
            provider: azure-active-directory
            client-name: client-1-resource-server-2
            client-id: ${CLIENT_1_CLIENT_ID}
            client-secret: ${CLIENT_1_CLIENT_SECRET}
            scope: openid, profile, api://${RESOURCE_SERVER_2_CLIENT_ID}/resource-server-2.scope-1 # Refs: https://docs.microsoft.com/azure/active-directory/develop/v2-permissions-and-consent#openid-connect-scopes
            redirect-uri: http://localhost:8080/login/oauth2/code/
  profiles:
    active: develop
