= Tutorial of using Azure Active Directory B2C by Spring Security
:toc:

From this tutorial, you will learn how to use Azure Active Directory B2C by Spring Security.

== Prerequisites
- https://azure.microsoft.com/free[Azure Subscription]
- https://docs.microsoft.com/java/azure/jdk/?view=azure-java-stable[Java Development Kit (JDK)] with version 8 or above

[[create-azure-active-directory-B2C-resources]]

== Prepare Azure Active Directory B2C resources

=== Create your Azure Active Directory B2C tenant

Follow the guide of https://docs.microsoft.com/azure/active-directory-b2c/tutorial-create-tenant[AAD B2C tenant creation].

=== Register your Azure Active Directory B2C application

Follow the guide of https://docs.microsoft.com/azure/active-directory-b2c/tutorial-register-applications[AAD B2C application registry].
Please ensure that your b2c application's `Redirect URL` is configured to `http://localhost:8080/login/oauth2/code/`.
In order to jump to the correct page (home) after `profile-edit` and `password-reset`, we need to add `http://localhost:8080/` in the redirect uri too.
You can add additional `Redirect URL` with https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app#add-a-redirect-uri[Add Redirect URL].

=== Create user flows

Follow the guide of https://docs.microsoft.com/azure/active-directory-b2c/tutorial-create-user-flows[AAD B2C user flows creation].

=== Enable forgot password

Follow the guide of https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-user-flow#self-service-password-reset-recommended[AAD B2C enable forgot password].

=== Enable profile edit

Follow the guide of https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-profile-editing-policy?pivots=b2c-user-flow[AAD B2C set up a profile edit flow].

=== Enable password reset

Follow the guide of https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-user-flow#create-a-password-reset-user-flow[AAD B2C set up a password reset user flow]

== Work as web application

[[work-application-simple-sample]]
=== Web application simple sample

Sample project: <<./azure-ad-b2c-sample-1-web-application-simple-sample/README.adoc#chapter-link, web-application-1-simple-sample>>

==== Fill necessary values in sample project.

1. Fill necessary values in `application.yml`, like `${your-jwk-set-uri}`.

2. Fill necessary values in `home.html`, like `${your-tenant-name}`.

==== Boot up the application

Lunch the sample project, then open `http://localhost:8080` by browser.
You are then redirected to the default _auto-generated_ login page. You can sign in or sign up with your account.

Then, you can edit your profile with the button `Profile edit` or reset your password with `Password reset`.

[[Web-application-with-scopes]]
=== Web application with scopes

Sample project: <<./azure-ad-b2c-sample-2-web-application-validate-scopes/README.adoc#chapter-link, web-application-2-with-scopes>>

Compared with the previous sample, this sample updates the `application.yml`, `SampleController.java`.

==== Configure scopes for application

Configure scopes `Delegated.Permission.Scope1` for application with https://docs.microsoft.com/azure/active-directory-b2c/add-web-api-application?tabs=app-reg-ga#configure-scopes[Configure-scopes].
Then grant admin consent for application with https://docs.microsoft.com/azure/active-directory-b2c/add-web-api-application?tabs=app-reg-ga#grant-permissions[Grant-admin-consent].

==== Fill necessary values in sample project.

1. Fill necessary values in `application.yml`, like `${your-jwk-set-uri}`.

2. Fill necessary values in `home.html`, like `${your-tenant-name}`.

==== Boot up the application

Lunch the sample project, then open `http://localhost:8080` by browser.

Compared with the previous sample, this sample can validate scopes.
Open `http://localhost:8080/hello` by browser, the account has authority for the resource server.

[[Web-application-with-client-credentials]]
=== Web application with client credentials

Sample project: <<./azure-ad-b2c-sample-3-web-application-client-credentials/README.adoc#chapter-link, web-application-3-with-client-credentials>>

Compared with the previous sample, this sample updates the `application.yml`, `SampleController.java` and add the `WebClientConfig.java`.
`WebClientConfig.java` will provide a WebClient, which will help to visit other resource servers with access token.

==== Configure roles for application

Configure Role `Application.Permission.Role1` for application with https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps#app-manifest-editor[Configure-roles-for-application].
https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-overview#consumer-user[Consumer-user] cannot access Azure resources, but we can https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps#example-application-app-role[assign-roles-to-application].

==== Fill necessary values in sample project.

1. Fill necessary values in `application.yml`, like `${your-jwk-set-uri}`.

2. Fill necessary values in `home.html`, like `${your-tenant-name}`.

==== Boot up the application

Lunch the sample project, then open `http://localhost:8080` by browser.

Compared with the previous example, this sample adds a client to obtain a token for your custom resource.
You can access the resource server by the scopes obtained from this sample. You need to lunch related samples first.

Open `http://localhost:8080/resourceServer` by browser, and you will access the resource server which will validate your access token.
Please refer to <<Resource-server-simple-sample, Resource-server-simple-sample>>.

Open `http://localhost:8080/resourceServerValidateAudience` by browser, and you will access the resource server which will validate your access token's audience.
Please refer to <<Resource-server-validate-audience, Resource-server-validate-audience>>.

Open `http://localhost:8080/resourceServerWithScope` by browser, and you will access the resource server which will authorize with the `scp` claims in your access token.
Please refer to <<Resource-server-authorize-by-scopes, Resource-server-authorize-by-scopes>>.

Open `http://localhost:8080/resourceServerWithRoles` by browser, and you will access the resource server which will authorize with the `roles` claims in your access token.
Please refer to <<Resource-server-authorize-by-app-roles, Resource-server-authorize-by-app-roles>>.

Open `http://localhost:8080/resourceServerWithMultiTenant` by browser, and you will access the resource server which will authorize with the `scp` and `roles` claims in your access token.
Please refer to <<Resource-server-multi-tenant, Resource-server-multi-tenant>>.

[[Web-application-with-additional-parameters]]
=== Web application with additional parameters

Sample project: <<./azure-ad-b2c-sample-4-web-application-additional-parameters/README.adoc#chapter-link, web-application-4-with-additional-parameters>>

Compared with the previous sample, this sample updates the `WebSecurityConfiguration.java`.

==== Fill necessary values in sample project.

1. Fill necessary values in `application.yml`, like `${your-jwk-set-uri}`.

2. Fill necessary values in `home.html`, like `${your-tenant-name}`.

==== Boot up the application
Lunch the sample project, then open `http://localhost:8080` by browser.
Compared with the previous sample, this application just adds `additional-Parameters`.

[[work-as-resource-server]]
== Work as Resource Server

[[Resource-server-simple-sample]]
=== Resource server simple sample

Sample project: <<./azure-ad-b2c-sample-1-resource-server-simple-sample/README.adoc#chapter-link, resource-server-1-simple-sample>>

==== Fill necessary values in sample project.

1. Fill necessary values in `application.yml`, like `${your-jwk-set-uri}`.

==== Boot up the application

We need to get related access token before we access this resource server, we can get related access token from previous sample, please refer to <<Web-application-with-client-credentials, Web-application-with-client-credentials>>.
Lunch the sample project. Then open `http://localhost:8080/resourceServer` by browser. The browser will access <<Web application simple sample,Web application simple sample>> , and which will access this resource server by access token.

[[Resource-server-validate-audience]]
=== Resource server validate audience

Sample project: <<./azure-ad-b2c-sample-2-resource-server-validate-audience/README.adoc#chapter-link, resource-server-2-validate-audience>>

Compared with the previous sample, this sample updates the `application.yml` and `WebSecurityConfiguration.java`.

==== Fill necessary values in sample project.

1. Fill necessary values in `application.yml`, like `${your-jwk-set-uri}`.

==== Boot up the application

We need to get related access token before we access this resource server, we can get related access token from previous sample, please refer to <<Web-application-with-client-credentials, Web-application-with-client-credentials>>.
Lunch the sample project. Then open `http://localhost:8080/resourceServerValidateAudience` by browser. The browser will access <<Web application simple sample,Web application simple sample>>, and which will access this resource server by access token.
This resource server will validate the accessToken's audience.

[[Resource-server-authorize-by-scopes]]
=== Resource server authorize by scopes

Sample project: <<./azure-ad-b2c-sample-3-resource-server-authorize-by-scopes/README.adoc#chapter-link, resource-server-3-authorize-by-scopes>>

Compared with the previous sample, this sample updates the `application.yml`, `SampleController.java` and `WebSecurityConfiguration.java`.

==== Fill necessary values in sample project.

1. Fill necessary values in `application.yml`, like `${your-jwk-set-uri}`.

==== Boot up the application

We need to get related access token before we access this resource server, we can get related access token from previous sample, please refer to <<Web-application-with-client-credentials, Web-application-with-client-credentials>>.
Lunch the sample project. Then open `http://localhost:8080/resourceServerWithScope` by browser. The browser will access <<Web application with scopes,Web application with scopes>>, and which will access this resource server by access token.
This resource server will validate the accessToken's `scp` claim.

[[Resource-server-authorize-by-app-roles]]
=== Resource server authorize by app roles

Sample project: <<./azure-ad-b2c-sample-4-resource-server-authorize-by-app-roles/README.adoc#chapter-link, resource-server-4-authorize-by-app-roles>>

Compared with the previous sample, this sample updates the `application.yml`, `SampleController.java` and `WebSecurityConfiguration.java`.

==== Fill necessary values in sample project.

1. Fill necessary values in `application.yml`, like `${your-jwk-set-uri}`.

==== Boot up the application

We need to get related access token before we access this resource server, we can get related access token from previous sample, please refer to <<Web-application-with-client-credentials, Web-application-with-client-credentials>>.
Lunch the sample project. Then open `http://localhost:8080/resourceServerWithRoles` by browser. The browser will access <<Web application with client credentials,Web application with client credentials>>, and which will access this resource server by access token.
This resource server will validate the accessToken's `roles` claim.

[[Resource-server-multi-tenant]]
=== Resource server multi tenant

Sample project: <<./azure-ad-b2c-sample-5-resource-server-multi-tenant/README.adoc#chapter-link, resource-server-5-multi-tenant>>

Compared with the previous sample, this sample updates the `application.yml`, `SampleController.java` and `WebSecurityConfiguration.java`.

==== Fill necessary values in sample project.

1. Fill necessary values in `application.yml`, like `${your-jwk-set-uri}`.

==== Boot up the application

We need to get related access token before we access this resource server, we can get related access token from previous sample, please refer to <<Web-application-with-client-credentials, Web-application-with-client-credentials>>.
Lunch the sample project.
Open `http://localhost:8080/resourceServerWithMultiTenant` by browser.
Compared with the previous sample, this sample can validate accessToken with different issuers.