spring:
  cloud:
    azure:
      appconfiguration:
        endpoint: ${APPCONFIGURATION_ENDPOINT}

# Uncomment the compatibility verifier when building native image with the `shaded` profile.
#      compatibility-verifier:
#        enabled: false
