$env:SERVICEBUS_NAMESPACE_NAME_DLQ_QUQUE=$(terraform -chdir=terraform output -raw SERVICEBUS_NAMESPACE_NAME_DLQ_QUQUE)
$env:PRICING_TIER=$(terraform -chdir=terraform output -raw PRICING_TIER)

echo SERVICEBUS_NAMESPACE_NAME_DLQ_QUQUE=$env:SERVICEBUS_NAMESPACE_NAME_DLQ_QUQUE
echo PRICING_TIER=$env:PRICING_TIER
