export SERVICEBUS_NAMESPACE_NAME_DLQ_QUQUE=$(terraform -chdir=./terraform output -raw SERVICEBUS_NAMESPACE_NAME_DLQ_QUQUE)
export PRICING_TIER=$(terraform -chdir=./terraform output -raw PRICING_TIER)

echo SERVICEBUS_NAMESPACE_NAME_DLQ_QUQUE=$SERVICEBUS_NAMESPACE_NAME_DLQ_QUQUE
echo PRICING_TIER=$PRICING_TIER
