spring:
  cloud:
    azure:
      storage:
        blob:
          account-name: firstaccount
          container-name: first-container
          account-key: ddXFrZwup0CLOzxqWS4gLhAGJgwtLypBsRWuMVoIFvkvb94jahdeXP/BhQlWvZGkAGIuDT94O3VX+AStF/PByA==

extend:
  spring:
    cloud:
      azure:
        storage:
          blob:
            account-name: secondaccountdev
            container-name: second-container
            account-key: ddXFrZwup0CLOzxqWS4gLhAGJgwtLypBsRWuMVoIFvkvb94jahdeXP/BhQlWvZGkAGIuDT94O3VX+AStF/PByA==
