# If we configure the spring.cloud.azure.active-directory.client-id or spring.cloud.azure.active-directory.app-id-uri will be to check the audience.
# In v2.0 tokens, this is always the client ID of the API, while in v1.0 tokens it can be the client ID or the resource URI used in the request.
# If you are using v1.0 tokens, configure both to properly complete the audience validation.

server:
  port: 8082

spring:
  cloud:
    azure:
# Properties like spring.cloud.azure.credential.client-id are global properties.
# Properties like spring.cloud.azure.active-directory.credential.client-id are AAD properties.
# If AAD properties is not configured, global properties will be used.
#      credential:
#        client-id:
#      profile:
#        tenant-id:
      active-directory:
        enabled: true
        credential:
          client-id: ${AZURE_CLIENT_ID}
        profile:
          tenant-id: ${AZURE_TENANT_ID}
        app-id-uri:  ${APP_ID_URI}

