spring:
  cloud:
    azure:
      eventhubs:
        connection-string: ${AZURE_EVENTHUBS_CONNECTION_STRING}
    function:
      definition: consume;supply
    stream:
      bindings:
        consume-in-0:
          destination: ${EVENTHUBS_KAFKA}
          group: $Default
        supply-out-0:
          destination: ${EVENTHUBS_KAFKA}
      binders:
        kafka:
          environment:
            spring:
              main:
                sources: com.azure.spring.cloud.autoconfigure.eventhubs.kafka.AzureEventHubsKafkaAutoConfiguration
