spring:
  cloud:
    azure:
      cosmos:
        key: [your-cosmos-key]
        endpoint: [your-cosmos-endpoint]
        database: [your-cosmos-database]

management:
  health:
    azure-cosmos:
      enabled: true