spring:
  autoconfigure.exclude: com.azure.spring.cloud.autoconfigure.storage.blob.AzureStorageBlobResourceAutoConfiguration
  cloud:
    azure:
      storage:
        blob:
          account-name: firstaccount
          container-name: first-container
          account-key: ddXFrZwup0CLOzxqWS4gLhAGJgwtLypBsRWuMVoIFvkvb94jahdeXP/BhQlWvZGkAGIuDT94O3VX+AStF/PByA==

extend:
  spring:
    cloud:
      azure:
        storage:
          blob:
            account-name: secondaccountdev
            container-name: second-container
            account-key: GtyAqxhLwYtKnnd7QwJnT+uwNQHC0IxLd1robo08KWMCxzM4AJNqtYuqv2Jr6lgY3FksdNa7rFxs+AStOKojSg==
