spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: ${ENDPOINT_1}
            secret-keys:
              - sampleProperty1
              - samplePropertyInMultipleKeyVault
          property-sources[1]:
            endpoint: ${ENDPOINT_2}
            secret-keys:
              - sampleProperty2
