spring:
  cloud:
    azure:
      eventhubs:
        connection-string: [connection-string]
        processor:
          checkpoint-store:
            container-name: [container-name]
            account-name: [account-name]
            account-key: [account-key]