spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-source-enabled: true
          endpoint: ${ENDPOINT}

# Uncomment the compatibility verifier when building native image with the `shaded` profile.
#      compatibility-verifier:
#        enabled: false

