SET aad_auth_validate_oids_in_tenant = OFF;
CREATE AADUSER '%%AZ_MYSQL_AD_NON_ADMIN_USERNAME%%' IDENTIFIED BY '%%AZ_MYSQL_AD_NON_ADMIN_USERID%%';
GRANT ALL PRIVILEGES ON %%dbname%%.* TO '%%AZ_MYSQL_AD_NON_ADMIN_USERNAME%%'@'%';
FLUSH privileges;