spring:
  application:
    name: keyvault-ssl-bundles-web
  ssl:
    bundle:
      azure-keyvault:
        keyVaultBundle:
          key:
            alias: self-signed
          keystore:
            keyvault-ref: keyvault1
          truststore:
            keyvault-ref: keyvault1
            certificates-refresh-interval: 120s
        otherKeyVaultBundle:
          keystore:
            keyvault-ref: keyvault2
          truststore:
            keyvault-ref: keyvault2
            certificate-paths:
              custom: "classpath:local-custom"
  cloud:
    azure:
      keyvault:
        jca:
          connections:
            keyvault1:
              endpoint: ${KEY_VAULT_SSL_BUNDLES_KEYVAULT_URI_01}
              profile:
                tenant-id: ${KEY_VAULT_SSL_BUNDLES_TENANT_ID}
              credential:
                client-id: ${KEY_VAULT_SSL_BUNDLES_CLIENT_ID}
                client-secret: ${KEY_VAULT_SSL_BUNDLES_CLIENT_SECRET}
            keyvault2:
              endpoint: ${KEY_VAULT_SSL_BUNDLES_KEYVAULT_URI_02}
              profile:
                tenant-id: ${KEY_VAULT_SSL_BUNDLES_TENANT_ID}
              credential:
                client-id: ${KEY_VAULT_SSL_BUNDLES_CLIENT_ID}
                client-secret: ${KEY_VAULT_SSL_BUNDLES_CLIENT_SECRET}

server:
  port: 8444
  ssl:
    bundle: "keyVaultBundle"
logging.level:
  com.azure.security.keyvault.jca.KeyVaultKeyStore: debug
