server:
  port: 8081

spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: 12dee116-a388-4048-bb23-97173c2f5b6c
          client-certificate-path: D:\issues\keyvault\ad-starter-client-auth\encrypted-private-key-and-certificate.pfx
          client-certificate-password: myPassword1
        profile:
          tenant-id: 0a2ede99-b592-4e1c-a0ee-283b3a172a61
        app-id-uri: api://webapia
        authorization-clients:
          graph:
            scopes:
              - https://graph.microsoft.com/User.Read
          webapiB:         # When authorization-grant-type is null, on behalf of flow is used by default
            authorization-grant-type: on_behalf_of
            client-authentication-method: private_key_jwt
            scopes:
              - api://webapib/WebApiB.ExampleScope
