server:
  port: 8081

spring:
  cloud:
    azure:
# Properties like spring.cloud.azure.credential.client-id are global properties.
# Properties like spring.cloud.azure.active-directory.credential.client-id are AAD properties.
# If AAD properties is not configured, global properties will be used.
#      credential:
#        client-id:
#        client-secret:
#      profile:
#        tenant-id:
      active-directory:
        enabled: true
        credential:
          client-id: 12dee116-a388-4048-bb23-97173c2f5b6c
          client-secret: t~v8Q~tsfxm9.z9QZ9MyrE~DKW4TmDDzcewPNcaz
        profile:
          tenant-id: 0a2ede99-b592-4e1c-a0ee-283b3a172a61
        app-id-uri: api://webapia
        authorization-clients:
          graph:
            scopes:
              - https://graph.microsoft.com/User.Read
          webapiB:         # When authorization-grant-type is null, on behalf of flow is used by default
            authorization-grant-type: on_behalf_of
            scopes:
              - api://webapib/WebApiB.ExampleScope
