export SERVICEBUS_FULL_QUALIFIED_DOMAIN_NAME=$(terraform -chdir=./terraform output -raw SERVICEBUS_FULL_QUALIFIED_DOMAIN_NAME)
export PRICING_TIER=$(terraform -chdir=./terraform output -raw PRICING_TIER)

echo SERVICEBUS_FULL_QUALIFIED_DOMAIN_NAME=$SERVICEBUS_FULL_QUALIFIED_DOMAIN_NAME
echo PRICING_TIER=$PRICING_TIER
