export AZURE_SERVICEBUS_NAMESPACE=$(terraform -chdir=./terraform output -raw AZURE_SERVICEBUS_NAMESPACE)
export AZURE_SERVICEBUS_TOPIC_NAME=$(terraform -chdir=./terraform output -raw AZURE_SERVICEBUS_TOPIC_NAME)
export AZURE_SERVICEBUS_TOPIC_SUBSCRIPTION_NAME=$(terraform -chdir=./terraform output -raw AZURE_SERVICEBUS_TOPIC_SUBSCRIPTION_NAME)
export AZURE_SERVICEBUS_RESOURCE_GROUP=$(terraform -chdir=./terraform output -raw AZURE_SERVICEBUS_RESOURCE_GROUP)
export AZURE_SERVICEBUS_SUBSCRIPTION_ID=$(terraform -chdir=./terraform output -raw AZURE_SERVICEBUS_SUBSCRIPTION_ID)

echo AZURE_SERVICEBUS_NAMESPACE=$AZURE_SERVICEBUS_NAMESPACE
echo AZURE_SERVICEBUS_TOPIC_NAME=$AZURE_SERVICEBUS_TOPIC_NAME
echo AZURE_SERVICEBUS_TOPIC_SUBSCRIPTION_NAME=$AZURE_SERVICEBUS_TOPIC_SUBSCRIPTION_NAME
echo AZURE_SERVICEBUS_RESOURCE_GROUP=AZURE_SERVICEBUS_RESOURCE_GROUP
echo AZURE_SERVICEBUS_SUBSCRIPTION_ID=AZURE_SERVICEBUS_SUBSCRIPTION_ID
