$env:SERVICEBUS_NAMESPACE_NAME=$(terraform -chdir=terraform output -raw SERVICEBUS_NAMESPACE_NAME)
$env:PRICING_TIER=$(terraform -chdir=terraform output -raw PRICING_TIER)

echo SERVICEBUS_NAMESPACE_NAME=$env:SERVICEBUS_NAMESPACE_NAME
echo PRICING_TIER=$env:PRICING_TIER
