export SERVICEBUS_NAMESPACE_CONNECTION_STRING=$(terraform -chdir=./terraform output -raw SERVICEBUS_NAMESPACE_CONNECTION_STRING)
export PRICING_TIER=$(terraform -chdir=./terraform output -raw PRICING_TIER)

echo SERVICEBUS_NAMESPACE_CONNECTION_STRING=$SERVICEBUS_NAMESPACE_CONNECTION_STRING
echo PRICING_TIER=$PRICING_TIER
