$env:SERVICEBUS_NAMESPACE_CONNECTION_STRING=$(terraform -chdir=terraform output -raw SERVICEBUS_NAMESPACE_CONNECTION_STRING)
$env:PRICING_TIER=$(terraform -chdir=terraform output -raw PRICING_TIER)

echo SERVICEBUS_NAMESPACE_CONNECTION_STRING=$env:SERVICEBUS_NAMESPACE_CONNECTION_STRING
echo PRICING_TIER=$env:PRICING_TIER
