spring:
  jms:
    servicebus:
      connection-string: ${servicebus-namespace-connection-string}
      idle-timeout: 1800000
      pricing-tier: Standard

#spring.jms.servicebus.idle-timeout=${idle-timeout}


#spring.jms.servicebus.pricing-tier=${pricing-tier}
