spring:
  cloud:
    azure:
      profile:
        tenant-id: [tenant-id]
      credential:
        client-id: [client-id]
        client-secret: [client-secret]
      eventhubs:
        resource:
          resource-group: [resource-group]
        namespace: [namespace]
        processor:
          checkpoint-store:
            container-name: [container-name]
            account-name: [account-name]

