spring:
  cloud:
    azure:
      msi-enabled: true
      client-id: [the-id-of-managed-identity]
      resource-group: [ resource-group ]
      subscription-id: [ subscription-id ]
      eventhubs:
        namespace: [eventhub-namespace]
        checkpoint-storage-account: [checkpoint-storage-account]
        checkpoint-container: [checkpoint-container]

