spring:
  cloud:
    azure:
      credential:
        managed-identity-client-id: [ managed-identity-client-id ]
      profile:
        tenant-id: [ tenant-id ]
#        msi-enabled: true
#        client-id: [the-id-of-managed-identity]
#        resource-group: [ resource-group ]
#        subscription-id: [ subscription-id ]
      eventhubs:
        namespace: [eventhub-namespace]
        processor:
          checkpoint-store:
            container-name: [container-name]
            account-name: [account-name]

