my.servicebus.namespaces:
  - namespace: ${AZURE_SERVICEBUS_NAMESPACE_01}
    entity-type: queue
  - namespace: ${AZURE_SERVICEBUS_NAMESPACE_02}
    entity-type: queue

#reduce some noise
logging.level:
  com.azure.core: warn
  com.azure.identity: warn
  com.azure.messaging: warn