spring:
  cloud:
    azure:
      storage:
        queue:
          account-name: ${STORAGE_QUEUE_ACCOUNT_NAME}
          queue-name: test
# Uncomment the compatibility verifier when building native image with the `shaded` profile.
      compatibility-verifier:
        enabled: false
