spring:
  cloud:
    azure:
      credential:
        client-id: [ client-id ]
        client-secret: [ client-secret ]
        profile:
          tenant-id: [ tenant-id ]

    #     Uncomment below configurations if you want to enable auto creating resources.
    #      auto-create-resources: true
    #      region: [region]
    #      subscription-id: [subscription-id]
      servicebus:
        namespace: [ servicebus-namespace ]

    stream:
      function:
        definition: consume1;supply1;consume2;supply2
      bindings:
        consume1-in-0:
          destination: [ servicebus-topic-1-name ]
          group: [ servicebus-topic-1-subscription-name ]
        supply1-out-0:
          destination: [ servicebus-topic-1-name-same-as-above ]
        consume2-in-0:
          binder: servicebus-2
          destination: [ servicebus-queue-1-name ]
        supply2-out-0:
          binder: servicebus-2
          destination: [ servicebus-queue-1-name-same-as-above ]
      binders:
        servicebus-1:
          type: servicebus
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    connection-string: [ servicebus-namespace-1-connection-string ]
        servicebus-2:
          type: servicebus
          default-candidate: false
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    connection-string: [ servicebus-namespace-2-connection-string ]
      servicebus:
        bindings:
          consume1-out-0:
            producer:
              entity-type: topic
          consume2-out-0:
            producer:
              entity-type: queue
      poller:
        initial-delay: 0
        fixed-delay: 1000