spring:
  cloud:
    azure:
      profile:
        tenant-id: ${AZURE_TENANT_ID}
      credential:
        client-id: ${AZURE_CLIENT_ID}
        client-secret: ${AZURE_CLIENT_SECRET}
    stream:
      function:
        definition: consume1;supply1;consume2;supply2
      bindings:
        consume1-in-0:
          destination: ${AZURE_EVENTHUB_1_NAME}
          group: ${AZURE_EVENTHUB_CONSUMER_GROUP}
        supply1-out-0:
          destination: ${THE_SAME_EVENTHUB_1_NAME_AS_ABOVE]
        consume2-in-0:
          binder: eventhub-2
          destination: ${AZURE_EVENTHUB_2_NAME}
          group: ${AZURE_EVENTHUB_CONSUMER_GROUP}
        supply2-out-0:
          binder: eventhub-2
          destination: ${THE_SAME_EVENTHUB_2_NAME_AS_ABOVE}
      binders:
        eventhub-1:
          type: eventhub
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  eventhubs:
                    namespace: ${FIRST_EVENTHUB_NAMESPACE}
                    processor:
                      checkpoint-store:
                        container-name: ${AZURE_STORAGE_CONTAINER_NAME}
                        account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
        eventhub-2:
          type: eventhub
          default-candidate: false
          environment:
            spring:
              cloud:
                azure:
                  eventhubs:
                    namespace: ${SECOND_EVENTHUB_NAMESPACE}
                    processor:
                      checkpoint-store:
                        container-name: ${AZURE_STORAGE_CONTAINER_NAME}
                        account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
      eventhubs:
        bindings:
          consume1-in-0:
            consumer:
              checkpoint:
                mode: MANUAL
          consume2-in-0:
            consumer:
              checkpoint:
                mode: MANUAL
      poller:
        initial-delay: 0
        fixed-delay: 1000