spring:
  cloud:
    azure:
      profile:
        tenant-id: [ tenant-id ]
      credential:
        client-id: [ client-id ]
        client-secret: [ client-secret ]
        resource-group: ${resource-group]
#     Uncomment below configurations if you want to enable auto creating resources.
#      auto-create-resources: true
#      region: [region]
#      subscription-id: [subscription-id]
    stream:
      function:
        definition: consume1;supply1;consume2;supply2
      bindings:
        consume1-in-0:
          destination: [eventhub-1-name]
          group: [consumer-group]
        supply1-out-0:
          destination: [the-same-eventhub-1-name-as-above]
        consume2-in-0:
          binder: eventhub-2
          destination: [eventhub-1-name]
          group: [consumer-group]
        supply2-out-0:
          binder: eventhub-2
          destination: [the-same-eventhub-2-name-as-above]
      binders:
        eventhub-1:
          type: eventhub
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  eventhubs:
                    namespace: [first-eventhub-namespace]
                    processor:
                      checkpoint-store:
                        container-name: [ container-name ]
                        account-name: [ account-name ]
        eventhub-2:
          type: eventhub
          default-candidate: false
          environment:
            spring:
              cloud:
                azure:
                  eventhubs:
                    namespace: [second-eventhub-namespace]
                    processor:
                      checkpoint-store:
                        container-name: [ container-name ]
                        account-name: [ account-name ]
      eventhubs:
        bindings:
          consume1-in-0:
            consumer:
              checkpoint-mode: MANUAL
          consume2-in-0:
            consumer:
              checkpoint-mode: MANUAL
      poller:
        initial-delay: 0
        fixed-delay: 1000
