spring:
  profiles:
    active: manual
  cloud:
    stream:
      function:
        definition: consume1;supply1;consume2;supply2
      bindings:
        consume1-in-0:
          destination: [eventhub-1-name]
          group: [consumer-group]
        supply1-out-0:
          destination: [the-same-eventhub-1-name-as-above]
        consume2-in-0:
          binder: eventhub-2
          destination: [eventhub-2-name]
          group: [consumer-group]
        supply2-out-0:
          binder: eventhub-2
          destination: [the-same-eventhub-2-name-as-above]

      binders:
        eventhub-1:
          type: eventhubs
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  eventhubs:
                    connection-string: [connection-string-of-first-eventhub-namespace]
                    processor:
                      checkpoint-store:
                        container-name: [container-name]
                        account-name: [account-name]
                        account-key: [account-key]
        eventhub-2:
          type: eventhubs
          default-candidate: false
          environment:
            spring:
              cloud:
                azure:
                  eventhubs:
                    connection-string: [connection-string-of-second-eventhub-namespace]
                    processor:
                      checkpoint-store:
                        container-name: [container-2-name]
                        account-name: [account-name]
                        account-key: [account-key]
      eventhubs:
        bindings:
          consume1-in-0:
            consumer:
              checkpoint:
                mode: MANUAL
          consume2-in-0:
            consumer:
              checkpoint:
                mode: MANUAL
      poller:
        initial-delay: 0
        fixed-delay: 1000
