spring:
  cloud:
    azure:
      credential:
        managed-identity-client-id: [ managed-identity-client-id ]
      profile:
        tenant-id: [ tenant-id ]
#     Uncomment below configurations if you want to enable auto creating resources.
#      auto-create-resources: true
#      environment: Azure
#      region: [ region ]
      eventhubs:
        namespace: [eventhub-namespace]
        processor:
          checkpoint-store:
            container-name: [ container-name ]
            account-name: [ account-name ]
    stream:
      function:
        definition: consume;supply
      bindings:
        consume-in-0:
          destination: [eventhub-name]
          group: [consumer-group]
        supply-out-0:
          destination: [the-same-eventhub-name-as-above]

      eventhubs:
        bindings:
          consume-in-0:
            consumer:
              checkpoint-mode: MANUAL
      default:
        producer:
          errorChannelEnabled: true
      poller:
        initial-delay: 0
        fixed-delay: 1000
