# Storage account name length should be between 3 and 24 and use numbers and lower-case letters only
# Configuration
azure.storage:
  account-name: input-your-account-name
  account-key: input-your-secret-key
  blob-endpoint: input-your-blob-endpoint

