# Please fill these placeholders before run this application:
# 1. ${tenant-id}
# 2. ${resource-server-2-client-id}

logging:
  level:
    root: DEBUG
server:
  port: 8082
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://login.microsoftonline.com/${tenant-id}/discovery/v2.0/keys
          issuer-uri: https://login.microsoftonline.com/${tenant-id}/v2.0
          audience: ${resource-server-2-client-id}
