# Please fill these placeholders before running this application:
# 1. ${tenant-id}
# 4. ${resource-server-1-client-id}
# 5. ${resource-server-2-client-id}

logging:
  level:
    root: DEBUG
server:
  port: 8083
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: resource-server-1
        uri: http://localhost:8081
        predicates:
        - Path=/resource-server-1
      - id: resource-server-2
        uri: http://localhost:8082
        predicates:
        - Path=/resource-server-2
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://login.microsoftonline.com/${tenant-id}/discovery/v2.0/keys
          issuer-uri: https://login.microsoftonline.com/${tenant-id}/v2.0
          audiences: ${resource-server-1-client-id}, ${resource-server-2-client-id}
  profiles:
    active: develop
