
spring:
  cloud:
    azure:
# Properties like spring.cloud.azure.credential.client-id are global properties.
# Properties like spring.cloud.azure.active-directory.credential.client-id are Microsoft Entra ID properties.
# If Microsoft Entra ID properties is not configured, global properties will be used.
#      credential:
#        client-id:
      active-directory:
        enabled: true
        credential:
          client-id: ${AZURE_CLIENT_ID}
        session-stateless: true
        app-id-uri: ${APP_ID_URI}


