spring:
  cloud:
    azure:
      storage:
        queue:
          profile:
            subscription-id: [subscription-id]
          account-name: [storage-account]
          credential:
            client-id: [ the-id-of-managed-identity ]
          resource:
            resource-group: [resource-group]

