# Please fill these placeholders before run this application:
# 1. ${tenant-id}
# 2. ${client-1-client-id}
# 3. ${client-1-client-secret}
# 4. ${resource-server-1-client-id}

logging:
  level:
    root: DEBUG
server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        provider: # Refs: https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2login-common-oauth2-provider
          azure-active-directory:
            issuer-uri: https://login.microsoftonline.com/${tenant-id}/v2.0 # Refs: https://docs.spring.io/spring-security/site/docs/current/reference/html5/#webflux-oauth2-login-openid-provider-configuration
            user-name-attribute: name
        registration:
          client-1-resource-server-1:
            provider: azure-active-directory
            client-id: ${client-1-client-id}
            client-secret: ${client-1-client-secret}
            scope: openid, profile, offline_access, api://${resource-server-1-client-id}/resource-server-1.scope-1, # Refs: https://docs.microsoft.com/azure/active-directory/develop/v2-permissions-and-consent#openid-connect-scopes
            redirect-uri: http://localhost:8080/login/oauth2/code/