spring:
  cloud:
    azure:
      credential:
        client-id: ${AZURE_CLIENT_ID}
        client-secret: ${AZURE_CLIENT_SECRET}
      profile:
        tenant-id: ${AZURE_TENANT_ID}
      servicebus:
        namespace: ${AZURE_SERVICEBUS_NAMESPACE}
    stream:
      function:
        definition: consume;supply
      bindings:
        consume-in-0:
          destination: ${AZURE_SERVICEBUS_TOPIC_NAME}
          group: ${AZURE_SERVICEBUS_TOPIC_SUBSCRIPTION_NAME}
        supply-out-0:
          destination: ${AZURE_SERVICEBUS_TOPIC_NAME}
      servicebus:
        bindings:
          consume-in-0:
            consumer:
              checkpoint-mode: MANUAL
          supply-out-0:
            producer:
              entity-type: topic
      poller:
        fixed-delay: 1000
        initial-delay: 0
