export AZURE_SERVICEBUS_NAMESPACE_01=$(terraform -chdir=./terraform output -raw AZURE_SERVICEBUS_NAMESPACE_01)
export AZURE_SERVICEBUS_NAMESPACE_02=$(terraform -chdir=./terraform output -raw AZURE_SERVICEBUS_NAMESPACE_02)
export AZURE_SERVICEBUS_TOPIC_NAME=$(terraform -chdir=./terraform output -raw AZURE_SERVICEBUS_TOPIC_NAME)
export AZURE_SERVICEBUS_TOPIC_SUBSCRIPTION_NAME=$(terraform -chdir=./terraform output -raw AZURE_SERVICEBUS_TOPIC_SUBSCRIPTION_NAME)
export AZURE_SERVICEBUS_QUEUE_NAME=$(terraform -chdir=./terraform output -raw AZURE_SERVICEBUS_QUEUE_NAME)

echo AZURE_SERVICEBUS_NAMESPACE_01=$AZURE_SERVICEBUS_NAMESPACE_01
echo AZURE_SERVICEBUS_NAMESPACE_02=$AZURE_SERVICEBUS_NAMESPACE_02
echo AZURE_SERVICEBUS_TOPIC_NAME=$AZURE_SERVICEBUS_TOPIC_NAME
echo AZURE_SERVICEBUS_TOPIC_SUBSCRIPTION_NAME=$AZURE_SERVICEBUS_TOPIC_SUBSCRIPTION_NAME
echo AZURE_SERVICEBUS_QUEUE_NAME=$AZURE_SERVICEBUS_QUEUE_NAME
