cosmos:
  uri: ${ACCOUNT_HOST}
  key: ${ACCOUNT_KEY}
  secondaryKey: ${SECONDARY_ACCOUNT_KEY}
  # Set to true to populate query metrics - 
  # NOTE: this will NOT give request information about point reads (only queries)
  # See https://aka.ms/PointReadsInSpring for more information on the difference between point reads and queries.
  queryMetricsEnabled: true
dynamic:
  collection:
    name: spel-property-collection

