name: Markdown Links Check

on: [push, pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-22.04 #workaround https://github.com/UmbrellaDocs/action-linkspector/issues/32
    steps:
      - uses: actions/checkout@master
      - uses: umbrelladocs/action-linkspector@v1.1.3
        with:
          reporter: github-pr-review
          config_file: '.github/workflows/.linkspector.yml'
          level: error
          fail_on_error: true
